### PR TITLE
Update Spammers.txt

### PR DESCRIPTION
**Pull request by Artlinkz**
New list of spam referrals sites.

### CODE REVIEW

**Comment by Artlinkz** [comment]
Please check these new bunch of URLs spam referrals.
this list is very useful guys thanks, found it by using the WP plugin (Stop Spam Referrals)

**Comment by Artlinkz** [comment]
Yep definitely, I'll keep posting up new URL's here... much more convenient than enter them manually on each WP installs... 
I can help for a nice plugin logo redesign if you need. 
just let me know :)

**Comment by Tsuroerusu** [comment]
A maintainer of this repository has to merge it first. Hopefully one of them will see this ASAP.

**Comment by spmedia** [comment]
I am wary of mass merging these for a few different reasons.

1) Please go through these and double check the validity of them. Make sure there are no regular websites in here. For example, I found **r.search.yahoo.com** in there. Come on now 🤔. ya.ru is also a legit and huge RU site.
2) Do not add any subdomain urls. It will automatically do that. Only add root domains.
3) Insert them into the list in alphabetical order.

Fix these issues and I will review them again.

**Comment by farfallosa** [comment]
Could you please add  progressive-seo.com to the referral-spam list? Thanks

**Pull request closed without merging**
